---
- hosts: 172.31.89.182
  become: yes
  gather_facts: yes
  tasks: 
   - name: creating a file
     file:
      path: /home/surya/file1
      state: touch

   - name: copying a file
     copy: 
      src: java.yml
      dest: /home/surya/

   - name: internet files
     get_url:
      url: hhttps://ftp.unicamp.br/pub/apache/tomcat/tomcat-8/v8.5.73/bin/apache-tomcat-8.5.73-deployer.tar.gz
      dest: home/surya/tomcat-9.0.34.tar.gz