---
- hosts: newserver
  become: yes
  tasks:
   - name: install http on node
     apt:
       name: apache2
       state: absent
   - name: start the web server
     service:
       name: apache2
       state: started

